---
- name: Automated Deployment and Configuration with Ansible
  hosts: hng
  become: yes

  vars:
    git_branch: "devops"
    git_repo: "https://github.com/hngprojects/hng_boilerplate_python_fastapi_web.git"
    local_repo: "/opt/stage_5b"
    venv: "venv"
    log_dir: "/var/log/stage_5b"
    postgres_cred_dir: "/var/secrets"
    log_stderr: "/var/log/stage_5b/error.log"
    log_stdout: "/var/log/stage_5b/out.log"
    postgres_cred: "/var/secrets/pg_pw.txt"
    deploy_user: "hng"
    deploy_passwd: "{{ deploy_user }}"
    app_port: 3000
    nginx_port: 80
    postgres_db: "database"
    postgres_admin_user: "admin"
    postgres_admin_password: "passwd"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Check if sudo group exists
      command: getent group sudo
      register: sudo_group
      ignore_errors: true

    - name: Create sudo group if it doesn't exist
      group:
        name: sudo
        state: present
      when: sudo_group.rc != 0

    - name: Ensure sudo group has sudo privileges
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL:ALL) ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Install whois package
      apt:
        name: whois
        state: present

    - name: Generate password hash
      command: "mkpasswd --method=SHA-512 {{ deploy_passwd }}"
      register: hashed_password
      no_log: true

    - name: Create deployment user
      user:
        name: "{{ deploy_user }}"
        groups: sudo
        append: yes
        state: present
        shell: /bin/bash
        password: "{{ hashed_password.stdout }}"

    - name: Grant deployment user sudo privileges without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ deploy_user }}'
        line: '{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create log directory
      file:
        path: "{{ log_dir }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0755'

    - name: Create local repository directory
      file:
        path: "{{ local_repo }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0755'

    - name: Create PostgreSQL credentials directory
      file:
        path: "{{ postgres_cred_dir }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0755'

    - name: Ensure log files are present
      file:
        path: "{{ item }}"
        state: touch
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0644'
      loop:
        - "{{ log_stderr }}"
        - "{{ log_stdout }}"

    - name: Ensure PostgreSQL credentials file is present
      file:
        path: "{{ postgres_cred }}"
        state: touch
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0600'

    # Step 5: Ensure required Python packages are installed
    - name: Ensure python3-venv is installed
      apt:
        name: python3-venv
        state: present

    - name: Ensure python3-psycopg2 is installed
      apt:
        name: python3-psycopg2
        state: present

    # Step 6: Clone the git repository
    - name: Clone the git repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ local_repo }}"
        version: "{{ git_branch }}"
        force: yes

    # Step 7: Create a virtual environment and install the required packages
    - name: Create virtual environment
      command: python3 -m venv "{{ local_repo }}/{{ venv }}"
      args:
        chdir: "{{ local_repo }}"

    - name: Install dependencies from requirements.txt
      pip:
        requirements: "{{ local_repo }}/requirements.txt"
        virtualenv: "{{ local_repo }}/{{ venv }}"

    # Step 8: Set up PostgreSQL
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    state: present
    login_user: "postgres"
    db: "postgres"


    - name: Create PostgreSQL admin user
      become: yes
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ postgres_admin_user }}"
        password: "{{ postgres_admin_password }}"
        db: "{{ postgres_db }}"
        priv: "ALL"
        state: present
        login_user: "postgres"
        login_password: "{{ postgres_admin_password }}"

    - name: Save PostgreSQL admin credentials to file
      copy:
        content: |
          DB_TYPE=postgresql
          DB_NAME={{ postgres_db }}
          DB_USER={{ postgres_admin_user }}
          DB_PASSWORD={{ postgres_admin_password }}
          DB_HOST="localhost"
          DB_PORT=5432
          DB_URL=postgresql://{{ postgres_admin_user }}:{{ postgres_admin_password }}@localhost:5432/{{ postgres_db }}
        dest: "{{ postgres_cred }}"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0600'

    - name: Create a dummy table in PostgreSQL database
      become: yes
      become_user: postgres
      community.postgresql.postgresql_query:
        db: "{{ postgres_db }}"
        query: "CREATE TABLE IF NOT EXISTS dummy_table (column1 VARCHAR(255), column2 VARCHAR(255));"
        login_user: "postgres"
        login_password: "{{ postgres_admin_password }}"

    - name: Insert dummy data into PostgreSQL database
      become: yes
      become_user: postgres
      community.postgresql.postgresql_query:
        db: "{{ postgres_db }}"
        query: "INSERT INTO dummy_table (column1, column2) VALUES ('dummy1', 'dummy2');"
        login_user: "postgres"
        login_password: "{{ postgres_admin_password }}"

    # Step 9: Configure the application environment
    - name: Copy .env.sample to .env
      copy:
        src: "{{ local_repo }}/.env.sample"
        dest: "{{ local_repo }}/.env"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: '0644'

    - name: Update .env file with PostgreSQL details
      lineinfile:
        path: "{{ local_repo }}/.env"
        regexp: '^DB_URL='
        line: "DB_URL=postgresql://{{ postgres_admin_user }}:{{ postgres_admin_password }}@localhost:5432/{{ postgres_db }}"

    - name: Update .env file with database name
      lineinfile:
        path: "{{ local_repo }}/.env"
        regexp: '^DB_NAME='
        line: "DB_NAME={{ postgres_db }}"

    - name: Update .env file with database user
      lineinfile:
        path: "{{ local_repo }}/.env"
        regexp: '^DB_USER='
        line: "DB_USER={{ postgres_admin_user }}"

    - name: Update .env file with database password
      lineinfile:
        path: "{{ local_repo }}/.env"
        regexp: '^DB_PASSWORD='
        line: "DB_PASSWORD={{ postgres_admin_password }}"

    # Step 10: Run the FastAPI application
    - name: Run FastAPI application
      shell: |
        . {{ local_repo }}/{{ venv }}/bin/activate
        nohup uvicorn main:app --host 0.0.0.0 --port {{ app_port }} &
      args:
        chdir: "{{ local_repo }}"
      async: 0
      poll: 0

    # Step 11: Install and configure Nginx
    - name: Add Nginx signing key
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add Nginx APT repository
      apt_repository:
        repo: deb [arch=amd64] http://nginx.org/packages/ubuntu jammy nginx
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Nginx 1.26
      apt:
        name: nginx=1.26.0-1~jammy
        state: present

    - name: Remove default Nginx site configuration
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify:
        - restart nginx

    - name: Create new Nginx configuration from template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
